#!/sbin/busybox sh

# stop thermal
if [ "$(ps | grep "/system/bin/thermal-engine" | wc -l)" -ge "1" ]; then
	/system/bin/stop thermal-engine;
fi;
# set gpu devfreq to max
echo "578000000" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk

echo "thermal disable"

